export interface funcionarioData {
  key: number;
  id: number;
  Nome: string;
  Setor: string;
  Cargo: string;
}

export const contentPresidencia: funcionarioData[] = [
  {
    key: 1,
    id: 1,
    Nome: "Isaac Edington",
    Setor: "Presidência",
    Cargo: "Presidênte da Saltur",
  },
  {
    key: 2,
    id: 2,
    Nome: "Diana Silva",
    Setor: "Presidência",
    Cargo: "Secretária",
  },
  {
    key: 3,
    id: 3,
    Nome: "Flavia Faro",
    Setor: "Assessoria Estratégica",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 3,
    id: 3,
    Nome: "Marcelo Silva",
    Setor: "Assessoria Estratégica",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 4,
    id: 4,
    Nome: "Brenda Alves",
    Setor: "Assessoria de Comunicação",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 5,
    id: 5,
    Nome: "Andréa",
    Setor: "Assessoria de Comunicação",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 6,
    id: 6,
    Nome: "Mariane",
    Setor: "Assessoria de Comunicação",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 7,
    id: 7,
    Nome: "Jefersson Dias",
    Setor: "Assessoria de Comunicação",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 8,
    id: 8,
    Nome: "Anacele Soares",
    Setor: "Assessoria Jurídica",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 9,
    id: 9,
    Nome: "Salma kodsi",
    Setor: "Assessoria Jurídica",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 10,
    id: 10,
    Nome: "Bianca Viana",
    Setor: "Assessoria Jurídica",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 11,
    id: 11,
    Nome: "Rodrigo Cavalcante",
    Setor: "Assessoria de Marketing",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 12,
    id: 12,
    Nome: "Taiana Silva",
    Setor: "Assessoria de Marketing",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 13,
    id: 13,
    Nome: "Marcela Silva",
    Setor: "Assessoria de Marketing",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 14,
    id: 14,
    Nome: "Liana Oliva",
    Setor: "Movimento Salvador Vai de Bike",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 15,
    id: 15,
    Nome: "Elthom Pereira",
    Setor: "Movimento Salvador Vai de Bike",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 16,
    id: 16,
    Nome: "Daiane Martins",
    Setor: "Movimento Salvador Vai de Bike",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 17,
    id: 17,
    Nome: "Daniele Oliveira",
    Setor: "Movimento Salvador Vai de Bike",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 18,
    id: 18,
    Nome: "Marcos Santos",
    Setor: "Movimento Salvador Vai de Bike",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 19,
    id: 19,
    Nome: "André Ribeiro",
    Setor: "Núcleo de Tecnologia da Informação - NTI",
    Cargo: "Gerente de TI",
  },
  {
    key: 20,
    id: 20,
    Nome: "Rodrigo Oliveira",
    Setor: "Núcleo de Tecnologia da Informação - NTI",
    Cargo: "Técnico",
  },
  {
    key: 21,
    id: 21,
    Nome: "Alexandre Shyjada",
    Setor: "Núcleo de Tecnologia da Informação - NTI",
    Cargo: "Estagiário",
  },
  {
    key: 22,
    id: 22,
    Nome: "Isadora Ribeiro",
    Setor: "Núcleo de Tecnologia da Informação - NTI",
    Cargo: "Jovem Aprendiz",
  },
]

export const contentDirAdmFin: funcionarioData[] = [
  {
    key: 1,
    id: 1,
    Nome: "Pedro Rodamilans",
    Setor: "Diretoria Adm. Financeira",
    Cargo: "Diretor Administrativo Financeiro",
  },
  {
    key: 1,
    id: 1,
    Nome: "Patrícia Estrella",
    Setor: "Secretária",
    Cargo: "Diretor Administrativo Financeiro",
  },
  {
    key: 2,
    id: 2,
    Nome: "Branca Figueiredo",
    Setor: "Gerência Administrativa",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 2,
    id: 2,
    Nome: "Carla Lima",
    Setor: "Gerência Administrativa",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 2,
    id: 2,
    Nome: "Nevolandia Oliveira",
    Setor: "Gerência Administrativa",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 2,
    id: 2,
    Nome: "Ana Cristina Pires",
    Setor: "Gerência Administrativa",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 2,
    id: 2,
    Nome: "Rita ventura",
    Setor: "Gerência Administrativa",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 2,
    id: 2,
    Nome: "Almiro Sales",
    Setor: "Gerência Administrativa",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 3,
    id: 3,
    Nome: "Narcizo Almeida",
    Setor: "COPES/RH",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 3,
    id: 3,
    Nome: "Narcizo Almeida",
    Setor: "COPES/RH",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 3,
    id: 3,
    Nome: "Alessandra queiroz",
    Setor: "COPES/RH",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 3,
    id: 3,
    Nome: "Pedro Souza",
    Setor: "COPES/RH",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 4,
    id: 4,
    Nome: "Alex Saldanha",
    Setor: "Contratos",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 4,
    id: 4,
    Nome: "Amaro Junior",
    Setor: "Contratos",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 4,
    id: 4,
    Nome: "Elisabeth Coelho",
    Setor: "Contratos",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 5,
    id: 5,
    Nome: "Lorem Ipsum Dolor",
    Setor: "Almoxarifado",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 6,
    id: 6,
    Nome: "Lorem Ipsum Dolor",
    Setor: "Transporte",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 7,
    id: 7,
    Nome: "Lorem Ipsum Dolor",
    Setor: "SERGE",
    Cargo: "Lorem Ipsum Dolor",
  },
]

export const contentDirEventos: funcionarioData[] = [
  {
    key: 1,
    id: 1,
    Nome: "Lorem Ipsum Dolor",
    Setor: "Diretoria de Eventos",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 2,
    id: 2,
    Nome: "Lorem Ipsum Dolor",
    Setor: "Gerência de Eventos",
    Cargo: "Lorem Ipsum Dolor",
  },
  {
    key: 3,
    id: 3,
    Nome: "Lorem Ipsum Dolor",
    Setor: "Gerência do Carnaval",
    Cargo: "Lorem Ipsum Dolor",
  },
]